FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-devel


RUN apt-get  clean
RUN apt-get update -y
RUN apt-get  -y install git


RUN pip install danspeech
RUN pip install django

WORKDIR /workingdir
RUN git clone https://github.com/danspeech/danspeechdemo
WORKDIR /workingdir/danspeechdemo
RUN pip install .


