FROM pytorch/pytorch

# FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-devel
# From calmzone/pytorch_cuda101
# 

# To fix the nvidia thing, look in https://askubuntu.com/questions/1132090/i-am-not-able-to-install-anything-in-ubuntu

#  ... an alternative fix here


# RUN  rm -f rm /etc/apt/sources.list.d/cuda.list
RUN apt-get  clean
RUN apt-get update -y
RUN   apt-get  -y install git

# RUN apt-get install -y software-properties-common
# RUN add-apt-repository -r "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"


RUN apt-get install -y apt-utils
# RUN apt install -f

# dpkg: error processing archive /tmp/apt-dpkg-install-cpZZYd/221-nvidia-cuda-dev_9.1.85-3ubuntu1_amd64.deb (--unpack):
# trying to overwrite '/usr/include/cublas.h', which is also in package libcublas-dev 10.2.1.243-1


RUN apt-get install -y nvidia-cuda-dev
RUN apt-get install -y nvidia-cuda-toolkit

RUN  apt install -y libprotobuf-dev protobuf-compiler
RUN  apt install -y libc-bin

# These are probably not necessary
# RUN  apt install -y libnvidia
# RUN  apt install -y libfs

RUN apt install -y cmake
RUN apt install -y  tmux
RUN apt-get install -y gcc-5 g++-5


RUN pip install matplotlib
RUN pip install jupyter
RUN pip install ipykernel
RUN pip install --user ipykernel

RUN conda create --name pytorchgpu
# RUN conda init bash
SHELL ["conda", "run", "-n", "pytorchgpu", "/bin/bash", "-c"]

# Already exists in pytorch101
RUN   python -m ipykernel install --user --name=pytorchgpu

# Can be put  on same line
RUN pip install danspeech
RUN pip install ctcdecode


##
## Installing warp-ctc
##

WORKDIR /workspace

RUN  git clone https://github.com/SeanNaren/warp-ctc.git

WORKDIR /workspace/warp-ctc/build
RUN CC=gcc-5 cmake ..
RUN make


##
## Pytorch binding
##
ENV  CUDA_HOME /usr/local/cuda
WORKDIR /workspace/warp-ctc/pytorch_binding
RUN python setup.py install


##
##  Installing Apex
##
WORKDIR /workspace
RUN  git clone --recursive https://github.com/NVIDIA/apex.git
WORKDIR /workplace/apex
RUN pip install . 


##
##  Installing danspeech training
##
WORKDIR /workplace
RUN git clone https://github.com/danspeech/danspeech_training
WORKDIR /workplace/danspeech_training
RUN git clone https://github.com/SeanNaren/warp-ctc.git

# Edit ut warp-ctc version requirement first. It'll be installed manualy later
RUN  grep -v warp-ctc < env_train.yml > env_train.yml


RUN  conda env create -n training -f env_train.yml
# SHELL ["conda", "run", "-n", "training", "/bin/bash", "-c"]
WORKDIR /workplace/danspeech_training/warp-ctc


RUN  CC=gcc-5 cmake ..
RUN  make

##
##  Warp-ctc for pytorch
##

## XXX Some parts are missing here!
# WORKDIR /workplace/warp-ctc-pytorch/warpctc/core/build
# ENV Torch_DIR /opt/conda/envs/training/lib/python3.6/site-packages/torch/share/cmake/Torch
# RUN CC=gcc-5 cmake ..
# RUN make



#   # extendingpython path to includedanspeech  training directories
#   #309  cd /opt/conda/envs/training/lib/python3.6/site-packages/
#   #310  vim extend_path.pth
